// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dataclay/proto/metadata/metadata.proto

package es.bsc.dataclay.proto.metadata;

public interface GetAllBackendsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dataclay.proto.metadata.GetAllBackendsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;string, .dataclay.proto.common.Backend&gt; backends = 1;</code>
   */
  int getBackendsCount();
  /**
   * <code>map&lt;string, .dataclay.proto.common.Backend&gt; backends = 1;</code>
   */
  boolean containsBackends(
      java.lang.String key);
  /**
   * Use {@link #getBackendsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, es.bsc.dataclay.proto.common.Backend>
  getBackends();
  /**
   * <code>map&lt;string, .dataclay.proto.common.Backend&gt; backends = 1;</code>
   */
  java.util.Map<java.lang.String, es.bsc.dataclay.proto.common.Backend>
  getBackendsMap();
  /**
   * <code>map&lt;string, .dataclay.proto.common.Backend&gt; backends = 1;</code>
   */
  /* nullable */
es.bsc.dataclay.proto.common.Backend getBackendsOrDefault(
      java.lang.String key,
      /* nullable */
es.bsc.dataclay.proto.common.Backend defaultValue);
  /**
   * <code>map&lt;string, .dataclay.proto.common.Backend&gt; backends = 1;</code>
   */
  es.bsc.dataclay.proto.common.Backend getBackendsOrThrow(
      java.lang.String key);
}
