// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dataclay/proto/metadata/metadata.proto

package es.bsc.dataclay.proto.metadata;

public interface GetAccountResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dataclay.proto.metadata.GetAccountResponse)
    com.google.protobuf.MessageOrBuilder {
}
