// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dataclay/proto/metadata/metadata.proto

package es.bsc.dataclay.proto.metadata;

public interface GetAllBackendsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dataclay.proto.metadata.GetAllBackendsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool from_backend = 1;</code>
   * @return The fromBackend.
   */
  boolean getFromBackend();
}
