// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dataclay/proto/metadata/metadata.proto

package es.bsc.dataclay.proto.metadata;

/**
 * Protobuf type {@code dataclay.proto.metadata.GetAccountResponse}
 */
public final class GetAccountResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:dataclay.proto.metadata.GetAccountResponse)
    GetAccountResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetAccountResponse.newBuilder() to construct.
  private GetAccountResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetAccountResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetAccountResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return es.bsc.dataclay.proto.metadata.Metadata.internal_static_dataclay_proto_metadata_GetAccountResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return es.bsc.dataclay.proto.metadata.Metadata.internal_static_dataclay_proto_metadata_GetAccountResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            es.bsc.dataclay.proto.metadata.GetAccountResponse.class, es.bsc.dataclay.proto.metadata.GetAccountResponse.Builder.class);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof es.bsc.dataclay.proto.metadata.GetAccountResponse)) {
      return super.equals(obj);
    }
    es.bsc.dataclay.proto.metadata.GetAccountResponse other = (es.bsc.dataclay.proto.metadata.GetAccountResponse) obj;

    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static es.bsc.dataclay.proto.metadata.GetAccountResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static es.bsc.dataclay.proto.metadata.GetAccountResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static es.bsc.dataclay.proto.metadata.GetAccountResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static es.bsc.dataclay.proto.metadata.GetAccountResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static es.bsc.dataclay.proto.metadata.GetAccountResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static es.bsc.dataclay.proto.metadata.GetAccountResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static es.bsc.dataclay.proto.metadata.GetAccountResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static es.bsc.dataclay.proto.metadata.GetAccountResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static es.bsc.dataclay.proto.metadata.GetAccountResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static es.bsc.dataclay.proto.metadata.GetAccountResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static es.bsc.dataclay.proto.metadata.GetAccountResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static es.bsc.dataclay.proto.metadata.GetAccountResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(es.bsc.dataclay.proto.metadata.GetAccountResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code dataclay.proto.metadata.GetAccountResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:dataclay.proto.metadata.GetAccountResponse)
      es.bsc.dataclay.proto.metadata.GetAccountResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return es.bsc.dataclay.proto.metadata.Metadata.internal_static_dataclay_proto_metadata_GetAccountResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return es.bsc.dataclay.proto.metadata.Metadata.internal_static_dataclay_proto_metadata_GetAccountResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              es.bsc.dataclay.proto.metadata.GetAccountResponse.class, es.bsc.dataclay.proto.metadata.GetAccountResponse.Builder.class);
    }

    // Construct using es.bsc.dataclay.proto.metadata.GetAccountResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return es.bsc.dataclay.proto.metadata.Metadata.internal_static_dataclay_proto_metadata_GetAccountResponse_descriptor;
    }

    @java.lang.Override
    public es.bsc.dataclay.proto.metadata.GetAccountResponse getDefaultInstanceForType() {
      return es.bsc.dataclay.proto.metadata.GetAccountResponse.getDefaultInstance();
    }

    @java.lang.Override
    public es.bsc.dataclay.proto.metadata.GetAccountResponse build() {
      es.bsc.dataclay.proto.metadata.GetAccountResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public es.bsc.dataclay.proto.metadata.GetAccountResponse buildPartial() {
      es.bsc.dataclay.proto.metadata.GetAccountResponse result = new es.bsc.dataclay.proto.metadata.GetAccountResponse(this);
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof es.bsc.dataclay.proto.metadata.GetAccountResponse) {
        return mergeFrom((es.bsc.dataclay.proto.metadata.GetAccountResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(es.bsc.dataclay.proto.metadata.GetAccountResponse other) {
      if (other == es.bsc.dataclay.proto.metadata.GetAccountResponse.getDefaultInstance()) return this;
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:dataclay.proto.metadata.GetAccountResponse)
  }

  // @@protoc_insertion_point(class_scope:dataclay.proto.metadata.GetAccountResponse)
  private static final es.bsc.dataclay.proto.metadata.GetAccountResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new es.bsc.dataclay.proto.metadata.GetAccountResponse();
  }

  public static es.bsc.dataclay.proto.metadata.GetAccountResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetAccountResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetAccountResponse>() {
    @java.lang.Override
    public GetAccountResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetAccountResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetAccountResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public es.bsc.dataclay.proto.metadata.GetAccountResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

