// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dataclay/proto/metadata/metadata.proto

package es.bsc.dataclay.proto.metadata;

public interface NewSessionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dataclay.proto.metadata.NewSessionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 1;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string password = 2;</code>
   * @return The password.
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 2;</code>
   * @return The bytes for password.
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <code>string dataset_name = 3;</code>
   * @return The datasetName.
   */
  java.lang.String getDatasetName();
  /**
   * <code>string dataset_name = 3;</code>
   * @return The bytes for datasetName.
   */
  com.google.protobuf.ByteString
      getDatasetNameBytes();
}
