version: '3.9'
services:

  redis:
    image: redis:latest
    ports:
      - 6379:6379

  metadata-service:
    image: "ghcr.io/bsc-dom/dataclay:dev"
    build:
      context: ../../
      dockerfile: Dockerfile.dev
    depends_on:
      - redis
      - otel-collector
    ports:
      - 16587:16587
    environment:
      - DATACLAY_KV_HOST=redis
      - DATACLAY_KV_PORT=6379
      - DATACLAY_PASSWORD=s3cret
      - DATACLAY_USERNAME=testuser
      - DATACLAY_DATASET=testdata
      - DATACLAY_METADATA_PORT=16587
      - DATACLAY_LOGLEVEL=DEBUG
      - DATACLAY_TRACING=true
      - DATACLAY_TRACING_EXPORTER=otlp
      - DATACLAY_SERVICE_NAME=metadata
      - DATACLAY_TRACING_HOST=otel-collector
    command: python -m dataclay.metadata
    volumes:
      - ../../:/pyclay:ro

  backend:
    image: "ghcr.io/bsc-dom/dataclay:dev"
    depends_on:
      - redis
      - otel-collector
    ports:
      - 6867:6867
    environment:
      - DATACLAY_KV_HOST=redis
      - DATACLAY_KV_PORT=6379
      - DATACLAY_BACKEND_PORT=6867
      - DATACLAY_LOGLEVEL=DEBUG
      - DATACLAY_TRACING=true
      - DATACLAY_TRACING_EXPORTER=otlp
      - DATACLAY_SERVICE_NAME=backend
      - DATACLAY_TRACING_HOST=otel-collector
    command: python -m dataclay.backend
    volumes:
      - ../../:/pyclay:ro

  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: [ "--config=/etc/otel-collector.yaml" ]
    ports:
      - 4317:4317  # otlp grpc
    volumes:
      - ./otel-json-exporter.yaml:/etc/otel-collector.yaml
      - ./traces/:/traces/

