services:

  redis:
    image: redis:latest
    ports:
      - 6379:6379

  metadata-service:
    image: "ghcr.io/bsc-dom/dataclay:dev"
    build:
      context: ../../../
      dockerfile: Dockerfile.dev
    depends_on:
      - redis
    ports:
      - 16587:16587
    environment:
      - DATACLAY_KV_HOST=redis
      - DATACLAY_METRICS=true
      - DATACLAY_METRICS_EXPORTER=pushgateway
      - DATACLAY_METRICS_HOST=pushgateway
      - DATACLAY_METRICS_PORT=9091
      - DATACLAY_LOGLEVEL=DEBUG
    command: python -m dataclay.metadata
    volumes:
      - ../../../:/app:ro

  backend:
    image: "ghcr.io/bsc-dom/dataclay:dev"
    depends_on:
      - redis
    ports:
      - 6867:6867
    environment:
      - DATACLAY_KV_HOST=redis
      - DATACLAY_METRICS=true
      - DATACLAY_METRICS_EXPORTER=pushgateway
      - DATACLAY_METRICS_HOST=pushgateway
      - DATACLAY_METRICS_PORT=9091
      - DATACLAY_LOGLEVEL=DEBUG
    command: python -m dataclay.backend
    volumes:
      - ../../../:/app:ro

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus.yaml
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver #todo: check if this is needed
      - --enable-feature=exemplar-storage #todo: check if this is needed

  pushgateway:
    image: prom/pushgateway:latest
    ports:
      - "9091:9091"

