# syntax=docker/dockerfile:1

ARG PYTHON_VERSION=3.10-bookworm

# install dataclay
FROM python:$PYTHON_VERSION
COPY . /app
RUN python -m pip install --upgrade pip \
  && python -m pip install -r /app/requirements-dev.txt -r /app/requirements-legacydeps.txt \
  && python -m pip install -e /app --no-deps

# prepare dataclay storage dir
RUN mkdir -p /data/storage; 

# set workdir and entrypoint
WORKDIR /workdir
