services:

  redis:
    image: redis:latest
    ports:
      - 6379:6379

  metadata-service:
    image: "ghcr.io/bsc-dom/dataclay:dev"
    depends_on:
      - redis
    ports:
      - 16587:16587
    environment:
      - DATACLAY_KV_HOST=redis
      - DATACLAY_PASSWORD=s3cret
      - DATACLAY_USERNAME=testuser
      - DATACLAY_DATASET=testdata
      - DATACLAY_LOGLEVEL=debug
    command: python -m dataclay.metadata
    volumes:
      - ../..:/app:ro

  backend:
    image: "ghcr.io/bsc-dom/dataclay:dev"
    depends_on:
      - redis
    environment:
      - DATACLAY_KV_HOST=redis
      - DATACLAY_LOGLEVEL=debug
    command: python -m dataclay.backend
    volumes:
      - ./model:/workdir/model:ro
      - ../..:/app:ro
