// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dataclay/proto/backend/backend.proto

package es.bsc.dataclay.proto.backend;

public interface CallActiveMethodRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dataclay.proto.backend.CallActiveMethodRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string session_id = 1;</code>
   * @return The sessionId.
   */
  java.lang.String getSessionId();
  /**
   * <code>string session_id = 1;</code>
   * @return The bytes for sessionId.
   */
  com.google.protobuf.ByteString
      getSessionIdBytes();

  /**
   * <code>string object_id = 2;</code>
   * @return The objectId.
   */
  java.lang.String getObjectId();
  /**
   * <code>string object_id = 2;</code>
   * @return The bytes for objectId.
   */
  com.google.protobuf.ByteString
      getObjectIdBytes();

  /**
   * <code>string method_name = 3;</code>
   * @return The methodName.
   */
  java.lang.String getMethodName();
  /**
   * <code>string method_name = 3;</code>
   * @return The bytes for methodName.
   */
  com.google.protobuf.ByteString
      getMethodNameBytes();

  /**
   * <code>bytes args = 4;</code>
   * @return The args.
   */
  com.google.protobuf.ByteString getArgs();

  /**
   * <code>bytes kwargs = 5;</code>
   * @return The kwargs.
   */
  com.google.protobuf.ByteString getKwargs();
}
