// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dataclay/proto/backend/backend.proto

package es.bsc.dataclay.proto.backend;

public interface ChangeObjectIdRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dataclay.proto.backend.ChangeObjectIdRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string object_id = 1;</code>
   * @return The objectId.
   */
  java.lang.String getObjectId();
  /**
   * <code>string object_id = 1;</code>
   * @return The bytes for objectId.
   */
  com.google.protobuf.ByteString
      getObjectIdBytes();

  /**
   * <code>string new_object_id = 2;</code>
   * @return The newObjectId.
   */
  java.lang.String getNewObjectId();
  /**
   * <code>string new_object_id = 2;</code>
   * @return The bytes for newObjectId.
   */
  com.google.protobuf.ByteString
      getNewObjectIdBytes();
}
