// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dataclay/proto/backend/backend.proto

package es.bsc.dataclay.proto.backend;

public interface ConsolidateObjectVersionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dataclay.proto.backend.ConsolidateObjectVersionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string object_id = 1;</code>
   * @return The objectId.
   */
  java.lang.String getObjectId();
  /**
   * <code>string object_id = 1;</code>
   * @return The bytes for objectId.
   */
  com.google.protobuf.ByteString
      getObjectIdBytes();
}
