// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dataclay/proto/backend/backend.proto

package es.bsc.dataclay.proto.backend;

public interface NewObjectVersionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dataclay.proto.backend.NewObjectVersionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string object_full_id = 1;</code>
   * @return The objectFullId.
   */
  java.lang.String getObjectFullId();
  /**
   * <code>string object_full_id = 1;</code>
   * @return The bytes for objectFullId.
   */
  com.google.protobuf.ByteString
      getObjectFullIdBytes();
}
