version: '3.9'
services: 

  redis:
    image: redis:latest

  metadata-service:
    image: "ghcr.io/bsc-dom/dataclay:dev"
    depends_on:
      - redis
    environment:
      - DATACLAY_KV_HOST=redis
      - DATACLAY_PASSWORD=s3cret
      - DATACLAY_USERNAME=testuser
      - DATACLAY_DATASET=testdata
      - DATACLAY_LOGLEVEL=INFO
    command: python -m dataclay.metadata

  backend:
    image: "ghcr.io/bsc-dom/dataclay:dev"
    depends_on:
      - redis
    environment:
      - DATACLAY_KV_HOST=redis
      - DATACLAY_LOGLEVEL=INFO
    command: python -m dataclay.backend
    volumes:
      - ./model:/workdir/model:ro

  proxy:
    image: "ghcr.io/bsc-dom/dataclay:dev"
    ports:
      - 8676:8676
    depends_on:
      - metadata-service
      - backend
    environment:
      - DATACLAY_PROXY_MDS_HOST=metadata-service
      - DATACLAY_KV_HOST=redis
      - DATACLAY_LOGLEVEL=DEBUG
      - DATACLAY_PROXY_OIDC_DISCOVERY_URL=http://keycloak:8080/realms/dataclay/.well-known/openid-configuration
      - KEYCLOAK_SERVER_URL=http://keycloak:8080
      - KEYCLOAK_CLIENT_ID=qwerty
      - KEYCLOAK_REALM_NAME=dataclay
      - KEYCLOAK_CLIENT_SECRET_KEY=rkqCwO97xxwoX9LSftO9hW4JXMrK932R
      - KEYCLOAK_RESOURCE_SERVER_ID=Default Resource
      - KEYCLOAK_AUDIENCE=Default Resource
      - PROMETHEUS_METRICS_DISABLED=True
      - SECURITY_DISABLED=False
    command: bash -c "pip install python-keycloak && python -m dataclay.proxy"
    volumes:
      - ./proxy_config.py:/workdir/proxy_config.py
      - ./middleware.py:/workdir/middleware.py
      - ./middleware_val.py:/workdir/middleware_val.py

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./keycloak-data:/opt/keycloak/data/import
    ports:
      - 8080:8080
    command: start-dev --import-realm
    

