// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dataclay/proto/common/common.proto

package es.bsc.dataclay.proto.common;

public final class Common {
  private Common() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dataclay_proto_common_Backend_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dataclay_proto_common_Backend_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dataclay_proto_common_ObjectMetadata_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dataclay_proto_common_ObjectMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dataclay_proto_common_Session_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dataclay_proto_common_Session_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dataclay_proto_common_Dataclay_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dataclay_proto_common_Dataclay_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dataclay_proto_common_Alias_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dataclay_proto_common_Alias_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"dataclay/proto/common/common.proto\022\025da" +
      "taclay.proto.common\"F\n\007Backend\022\n\n\002id\030\001 \001" +
      "(\t\022\014\n\004host\030\002 \001(\t\022\014\n\004port\030\003 \001(\005\022\023\n\013datacl" +
      "ay_id\030\004 \001(\t\"\306\001\n\016ObjectMetadata\022\n\n\002id\030\001 \001" +
      "(\t\022\024\n\014dataset_name\030\002 \001(\t\022\022\n\nclass_name\030\003" +
      " \001(\t\022\022\n\nbackend_id\030\004 \001(\t\022\033\n\023replica_back" +
      "end_ids\030\005 \003(\t\022\024\n\014is_read_only\030\006 \001(\010\022\032\n\022o" +
      "riginal_object_id\030\007 \001(\t\022\033\n\023versions_obje" +
      "ct_ids\030\010 \003(\t\"P\n\007Session\022\n\n\002id\030\001 \001(\t\022\020\n\010u" +
      "sername\030\002 \001(\t\022\024\n\014dataset_name\030\003 \001(\t\022\021\n\ti" +
      "s_active\030\004 \001(\010\"C\n\010Dataclay\022\n\n\002id\030\001 \001(\t\022\014" +
      "\n\004host\030\002 \001(\t\022\014\n\004port\030\003 \001(\005\022\017\n\007is_this\030\004 " +
      "\001(\010\">\n\005Alias\022\014\n\004name\030\001 \001(\t\022\024\n\014dataset_na" +
      "me\030\002 \001(\t\022\021\n\tobject_id\030\003 \001(\tB \n\034es.bsc.da" +
      "taclay.proto.commonP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_dataclay_proto_common_Backend_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_dataclay_proto_common_Backend_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dataclay_proto_common_Backend_descriptor,
        new java.lang.String[] { "Id", "Host", "Port", "DataclayId", });
    internal_static_dataclay_proto_common_ObjectMetadata_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_dataclay_proto_common_ObjectMetadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dataclay_proto_common_ObjectMetadata_descriptor,
        new java.lang.String[] { "Id", "DatasetName", "ClassName", "BackendId", "ReplicaBackendIds", "IsReadOnly", "OriginalObjectId", "VersionsObjectIds", });
    internal_static_dataclay_proto_common_Session_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_dataclay_proto_common_Session_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dataclay_proto_common_Session_descriptor,
        new java.lang.String[] { "Id", "Username", "DatasetName", "IsActive", });
    internal_static_dataclay_proto_common_Dataclay_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_dataclay_proto_common_Dataclay_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dataclay_proto_common_Dataclay_descriptor,
        new java.lang.String[] { "Id", "Host", "Port", "IsThis", });
    internal_static_dataclay_proto_common_Alias_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_dataclay_proto_common_Alias_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dataclay_proto_common_Alias_descriptor,
        new java.lang.String[] { "Name", "DatasetName", "ObjectId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
