version: 2.7.build{build}
max_jobs: 1
image: Ubuntu2004
environment:
  PYPI_USERNAME:
    secure: hFe1GQ6cN/KWeHe2+l/M1A==
  PYPI_PASSWORD:
    secure: MaoP5sVrqkkRaTHaeFcFLw==
  matrix:
  - PYTHON_VERSION: 3.6
  - PYTHON_VERSION: 3.8
  - PYTHON_VERSION: 3.10
install:
- sh: >-
    echo -e "[distutils]

    index-servers =

    \tpypitest


    [pypitest]

    repository: https://test.pypi.org/legacy/

    username: ${PYPI_USERNAME}

    password: ${PYPI_PASSWORD}" >> ~/.pypirc

    cat ~/.pypirc


    sudo apt-get update -y

    sudo apt-get install -y python$PYTHON_VERSION python3-pip python3-venv


    export PATH=/home/appveyor/.local/bin:$PATH

    pip3 install --upgrade pip

    pip3 install virtualenv
build_script:
- sh: "python3 -m venv ./venv \nsource ./venv/bin/activate \npip3 install --upgrade pip\npip3 install pytest wheel\npip3 install -e ."
test_script:
- sh: "source ./venv/bin/activate \npytest\ndeactivate"
deploy_script:
- sh: "source ./venv/bin/activate \npip3 install twine\nif [ \"$PYTHON_VERSION\" = \"3.6\" ]; then\n    ./release.sh -y --dev\nelse \n    echo \"Not deploying with python $PYTHON_VERSION\"\nfi\ndeactivate"
notifications:
- provider: Email
  to:
  - support-dataclay@bsc.es
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true