receivers:
  otlp:
    protocols:
      grpc:
exporters:
  file:
    path: $DATACLAY_JOB_PATH/otel-traces.json
  file/2:
    path: $DATACLAY_JOB_PATH/../otel-traces.json
processors:
  batch:
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [file, file/2]
      processors: [batch]
