# Preparation for setting up Redis cluster
- name: Start Redis instances
  shell: |
    nohup redis-server --protected-mode no \
      --appendonly yes \
      --cluster-enabled yes \
      --cluster-config-file nodes-{{ inventory_hostname }}.conf \
      --cluster-node-timeout {{ cluster_node_timeout }} \
      --port {{ redis_port }} \
      > {{ log_path }}/redis-{{ inventory_hostname }}.out 2>&1 &
  args:
    executable: /bin/bash
    chdir: "{{ job_path }}"

- name: Initialize Redis cluster
  vars:
    node_addresses: "{% for host in groups['redis'] %}{{ host }}:{{ redis_port }} {% endfor %}"
  command: redis-cli --cluster create {{ node_addresses }} --cluster-replicas {{ cluster_replicas }} --cluster-yes
  when: inventory_hostname == groups['redis'][0]  # Only run on the first instance to avoid conflict
