receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"

exporters:
  file:
    path: /traces/otel-traces.json

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [file]
      processors: [batch]
