- name: Deploy Metadata Service
  hosts: metadata
  gather_facts: false
  any_errors_fatal: true
  vars_files:
    - ./external_vars.yml
  environment: "{{ common_envs | combine(metadata_properties) }}"
  tasks:
    - name: Create job directories
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - "{{ dataclay_job_path }}"
        - "{{ dataclay_log_path }}"
        - "{{ dataclay_storage_path }}"

    - name: Start OTEL Collector
      shell: nohup otelcol --config {{ common_envs.DATACLAY_HOME }}/config/otel-json-exporter.yaml > {{ dataclay_log_path }}/otel.out 2>&1 &
      args:
        chdir: "{{ dataclay_job_path }}"
      when: common_envs.DATACLAY_TRACING|bool

    - name: Start redis-server
      shell: nohup redis-server --protected-mode no > {{ dataclay_log_path }}/redis.out 2>&1 &
      args:
        chdir: "{{ dataclay_job_path }}"

    - name: Start Metadata Service
      shell: nohup python -u -m dataclay.metadata > {{ dataclay_log_path }}/metadata.out 2>&1 &
      args:
        chdir: "{{ dataclay_job_path }}"

- name: Deploy Backends
  hosts: backends
  gather_facts: false
  vars:
    num: "{{ groups['backends'].index(inventory_hostname) }}"
  vars_files:
    - ./external_vars.yml
  environment: "{{ common_envs | combine(backend_properties) }}"
  tasks:
    - name: Start Backend Socket 0
      shell: nohup numactl -N 0 -m 0 -- python -u -m dataclay.backend > {{ dataclay_log_path }}/backend{{ num }}-s0.out 2>&1 &
      args:
        chdir: "{{ dataclay_job_path }}"
    - name: Start Backend Socket 1
      shell: nohup numactl -N 1 -m 1 -- python -u -m dataclay.backend > {{ dataclay_log_path }}/backend{{ num }}-s1.out 2>&1 &
      args:
        chdir: "{{ dataclay_job_path }}"
      environment:
        DATACLAY_BACKEND_PORT: "{{ backend_properties.DATACLAY_BACKEND_PORT | int + 1 }}"

