- name: Deploy Metadata Service
  hosts: metadata
  gather_facts: false
  vars_files:
    - ./external_vars.yml
  environment: "{{ common_envs | combine(metadata_properties) }}"
  tasks:
    - name: Create job directories
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - "{{ dataclay_job_path }}"
        - "{{ dataclay_log_path }}"
        - "{{ dataclay_storage_path }}"

    - name: Start redis-server
      shell: nohup redis-server --protected-mode no > {{ dataclay_log_path }}/redis.out &
      args:
        chdir: "{{ dataclay_job_path }}"

    - name: Start Metadata Service
      shell: nohup python -m dataclay.metadata &> {{ dataclay_log_path }}/mds.out &
      args:
        chdir: "{{ dataclay_job_path }}"
      ignore_errors: True

- name: Deploy Backends
  hosts: backends
  gather_facts: false
  vars:
    num: "{{ groups['backends'].index(inventory_hostname) }}"
  vars_files:
    - ./external_vars.yml
  environment: "{{ common_envs | combine(backend_properties) }}"
  tasks:
    - name: Start Backend
      shell: nohup python -u -m dataclay.backend &> {{ dataclay_log_path }}/backend{{ num }}.out &
      args:
        chdir: "{{ dataclay_job_path }}"
      ignore_errors: True
