global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "backend"
    static_configs:
      - targets: ["backend:8000"]
  - job_name: "metadata-service"
    static_configs:
      - targets: ["metadata-service:8000"]
  - job_name: "pushgateway"
    honor_labels: true
    static_configs:
      - targets: ["pushgateway:9091"]
